### ISSUE TITLE
Can't implement Private Route

### ISSUE THREAD

**Issue by 0nahid** [0nahid/user-post-admin#6]
react router dom version 6

**Comment by Musfick** [comment]
This might help

privateRoute.js
`function PrivateRoute({ children }) {
  const auth = useAuth();
  return auth ? children : <Navigate to="/login" />;
}`

app.js
`function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Public />} />
        <Route
          path="/private"
          element={
            <PrivateRoute>
              <Private />
            </PrivateRoute>
          }
        />
      </Routes>
    </BrowserRouter>
  );
}`

**Comment by 0nahid** [comment]
Thanks working

But how to redirect user to previous path?

**Comment by Musfick** [comment]
`import {useNavigate} from "react-router-dom"
const navigator = useNavigate()
onClick={() => navigator(-1)}
`

**Comment by 0nahid** [comment]
can you please create a pull request ?

**Comment by Musfick** [comment]
yeah sure

**Comment by 0nahid** [comment]
> yeah sure

Did you check out that brother?

**Comment by 0nahid** [comment]
`const handleGoogleSignIn = () => {
    signInWithGoogle()
      .then((result) => {
        navigator(-1);
      })
      .then((error) => {
        console.log(error);
      });
  };`
  
  solved
